# Generated by Django 5.2.4 on 2025-07-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kategori', models.CharField(max_length=50)),
                ('isi', models.TextField()),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('diproses', 'Diproses'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='diproses', max_length=20)),
            ],
        ),
    ]
