# Generated by Django 5.2.4 on 2025-07-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aduan',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='aduan_images/'),
        ),
        migrations.AlterField(
            model_name='aduan',
            name='kategori',
            field=models.CharField(choices=[('infrastruktur', 'Infrastruktur'), ('pelayanan', 'Pelayanan'), ('lingkungan', 'Lingkungan'), ('keamanan', 'Keamanan'), ('lainnya', 'Lainnya')], max_length=50),
        ),
        migrations.AlterField(
            model_name='aduan',
            name='status',
            field=models.CharField(choices=[('baru', 'Baru'), ('diproses', 'Diproses'), ('selesai', 'Selesai')], default='baru', max_length=20),
        ),
        migrations.AlterField(
            model_name='aduan',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
